Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 


Var


    nome ,sobrenome: caracter
Inicio

  escrevaL ("escreva seu nome por favor")
  //////////////////////////////q/////////
leia (nome)
  escreval("agora seu sobrenome")
leia (  sobrenome)
escreval("seu  nome completo é : ",nome + sobrenome)
   /////////////////////////////////////

//////////////////////////////////////////
Fimalgoritmo