Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
 n1,n2 : real


Inicio

escreval(" qual o primeiro numero que vc quer saber se e maior ou menor")
         leia(n1)
escreval(" qual o segundo numero que vc quer saber se e maior ou menor")
         leia(n2)
         
         se (n1 > n2)entao
         escreval(n1," é maior que" ,n2)
         senao
         escreval(n2," é maior que " , n1)
         fimse

Fimalgoritmo