Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2020
Var
n1  :real

Inicio
escreval( "qual foi a sua meta")
leia (n1)

se   n1 >=100 entao
escreval("parabens vc ganho com ", n1)
senao
escreval ("nao foi dessa vez falto",100-n1)
fimse


Fimalgoritmo
