Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

   n1 : real

Inicio
    escreval ("quantos quilimetros por hora vc esta  ")

    leia (n1)
    
    escreva (" vc estava a ",n1/(18/5))
      escreval (  "m/s" )
      escreva ("vc demorara mais ou menos ",434/ n1 )
            escreval     ("horas")
Fimalgoritmo



//434,4 km