Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2020
Var
// Seção de Declarações das variáveis 

   n : inteiro
Inicio

   escreval ("1")
   
para  n<- 1 ate 20 faca

        escreval ( "1/",n)
          fimpara
          
Fimalgoritmo